### ISSUE TITLE
Question: how to avoid enclosing tags when end of file hit?

### ISSUE THREAD

**Issue by irvingoujAtDevolution** [austinleroy/ebml-iterable#11]
Hello @austinleroy 

Your embl-iterable and webm-iterable are fantastic!

I am currently building an file based live streaming service using your crate. I noticed a behavior, that when end of file is hit, it will send enclosing master tags, which is a bit problematic for my usage, because my file hits eof often.[ I forked your repo and commented out a few line,](https://github.com/irvingoujAtDevolution/ebml-iterable/commit/837c4d190a8df95948c1d9f1e9294cce0dcf012b#diff-e5a68528365bec241b8d4b0679b64bbe772c7217b57e2f422a73d59cbc112f1cR463) which does not emit enclosing tags anymore. I'm wondering if there's a more idiomatic and desired approach to this? I'd be happy to contribute.

Best

**Comment by austinleroy** [comment]
Hello, and thank you for your interest!

I can see why the current behavior is problematic for your use case - this library wasn't initially developed for working with incomplete streams. Fair warning, there may be more EOF issues that crop up depending on where the stream is sliced.

As for the fix, I can think of two ways two go about it:

1. Remove the code where the iterator will emit "End" tags when reaching EOF, like in your commit.  However; I think this should be new opt-in behavior to prevent breaking existing uses.  This could be done with a new field on the TagIterator struct and a new function to enable it.
2. Add opt-in behavior so that the "private_read" function will block until it reads data.  This would be similar to option 1, except that the changes would be in the private_read function rather than read_next.

The first option has the advantage of passing control back to the application that uses this library; the second option would cause the process to hang while waiting for the reader to produce more data.
The second option has the advantage of catching _all_ potential EOF issues (e.g. if a stream reaches EOF in the middle of a tag) rather than just EOF at tag boundaries.

Personally, I think the first option still wins out in this case... the second option being a blocking operation hurts it too much to justify the better edge case handling.  I just wanted to mention it in case you had any other thoughts, or were thinking about doing something with the async iterator.

**Comment by irvingoujAtDevolution** [comment]
Thank you, I will take the first approach!
