### ISSUE TITLE
Better streaming support

### ISSUE THREAD

**Issue by madiele** [austinleroy/ebml-iterable#9]
Hi, I'm trying to use this crate to remux an ffmpeg output to add the Clues elements, my project requires that the output is streamed over HTTP so I need to be able to send stuff out even with un-closed tags, at the moment by reading the code my understanding is that everything is written to the destination only when flush is called or there are no open tags, problem with that is that the public flush() of the TagWriter also closes the tags ending the stream prematurely which make it impossible to send uncompleted data to the browser.

would it be possible to add a dirty flush or something like that?

**Comment by austinleroy** [comment]
Hey there - to answer your question, it isn't possible to write partial EBML and have it be correct.  EBML tags are encoded as `{<id><length><data>}`, meaning that the total length of the tag needs to be known before writing it to the stream.  For tags that contain other tags ("master" tags), this means that all of their children need to be fully defined before you're able to write the parent.

> everything is written to the destination only when flush is called or there are no open tags, problem with that is that the public flush() of the TagWriter also closes the tags ending the stream

This is exactly as intended, as it is impossible to correctly begin a tag in EBML if you don't have the tag in its entirety.

That said, there may be a couple of ways to solve your problem, depending on your requirements:
1. If you're legitimately writing data with an unknown length, you could use the 'write_unknown_size' function available on `TagWriter` to generate tags with the special Unknown length.  Any children of Unknown sized tags should get written to the destination as soon as possible.  However, there are only very specific tag types that should use the Unknown size, and using them when you shouldn't will probably break ebml parsers.
2. If you're actually sending data with a known length/size, and the problem is that you need to chunk the output to send it over http, you should buffer the output of `TagWriter`. You can then chunk the output buffer into sizes you want before sending the chunks over http.

Edit: markdown turned `{<id><length><data>}` into {}, so I fixed it

**Comment by madiele** [comment]
Thanks for the info! Got it, still learning the spec, I'll see if I manage to make it work
